## Using numpy for matrix.

In [1]:
import numpy as np

In [3]:
# Using numpy we can create heterogenous element. 
val = np.array([1,2,3], float)
for x in val:
    print(x,end=",")

1.0,2.0,3.0,

In [ ]:
# zeros
# ones

In [4]:
# 2-D Array
two = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in two:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [5]:
# 3-D Array
three = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for i in three:
    print(i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
